"""make_appendix_tables.py — LaTeX tables for the appendices (A/B/D/E/F series),
generated from the production report CSVs, the analysis parquet, and the code
constants so the manuscript numbers cannot drift from the analysis trees.

Complements make_manuscript_tables.py (main-text Tables 1–3 + moved tables) and
make_appendix_c_figures.py (tabC1–C8). Style matches the C-series tables
(Copernicus \\tophline/\\middlehline/\\bottomhline; longtable for >1-page
listings).

Tables written to manuscript/tables/:
  tabA1_fitting_config.tex       spectral-fit configuration and QC rules
  tabB1_cohort_attrition.tex     cohort inventory / attrition accounting
  tabB2_target_params.tex        target parameters and reference guards
  tabB3_label_noise_ceilings.tex label-noise reference levels by surface/regime
  tabD2_stationday_metrics.tex   complete AK-harmonized station-day metrics
  tabD3_significance_tests.tex   Wilcoxon + site-clustered bootstrap results
  tabD4_uncertainty_components.tex per-station-day uncertainty budget (+DL pool)
  tabD5_atom_legs.tex            ATom leg inventory and residuals
  tabD6_ship_cases.tex           ship case inventory and residuals
  tabE1_worsening_cases.tex      all worsening station-days, categorized
  tabE2_driver_strata.tex        extreme-decile performance by driver strata
  tabE3_cv_albedo.tex            held-out CV albedo cross-check
  tabE4_smoother_null.tex        full smoother-null numerical results
  tabF1_case_inventory.tex       vetted case-study inventory
  tabF2_plume_bounds.tex         per-case plume bounds and control nulls

NOT generated here — Table A2 (fit availability / failure accounting by band):
the combined feature parquet contains only successfully fitted soundings, so
band availability computed from it is trivially 100 %. The real accounting
(attempted vs converged fits, failure categories) needs a sweep over the
per-date fitting_details.h5 files, which live on CURC.

Usage:  PYTHONPATH=src python manuscript/scripts/make_appendix_tables.py [--only tabD4 ...]
"""
from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import pandas as pd

REPO = Path(__file__).resolve().parents[2]
TAG = "de_beta_nll_prof_reg_foldpca_o05l15_m5"
DEBASE = REPO / "results" / "model_comparison" / "deep_ensemble" / TAG
ATRAIN = DEBASE / "atrain"
OUT = REPO / "manuscript" / "tables"
PARQUET = REPO / "results" / "csv_collection" / "combined_2016_2020_dates.parquet"

TOPH, MIDH, BOTH = "\\tophline", "\\middlehline", "\\bottomhline"


# ---------------------------------------------------------------------------
# helpers
# ---------------------------------------------------------------------------

def write(name, text):
    OUT.mkdir(parents=True, exist_ok=True)
    p = OUT / name
    p.write_text("% Auto-generated by make_appendix_tables.py — do not hand-edit.\n"
                 + text)
    print(f"wrote {p.relative_to(REPO)}")


def table(colspec, header, rows, caption, label, notes=None, size="\\small",
          placement="t"):
    lines = [f"\\begin{{table}}[{placement}]",
             f"\\caption{{{caption}}}",
             f"\\label{{{label}}}", size,
             f"\\begin{{tabular}}{{{colspec}}}", TOPH,
             header + " \\\\", MIDH,
             *[r if r in (MIDH,) else r + " \\\\" for r in rows],
             BOTH, "\\end{tabular}"]
    if notes:
        lines.append(f"\\\\[3pt]\\parbox{{\\linewidth}}{{\\footnotesize {notes}}}")
    lines.append("\\end{table}")
    return "\n".join(lines) + "\n"


def longtable(colspec, header, rows, caption, label, notes=None,
              size="\\footnotesize", colsep=None):
    head = header + " \\\\"
    lines = ["\\begingroup" + size]
    if colsep:
        lines.append(f"\\setlength{{\\tabcolsep}}{{{colsep}}}")
    lines += [
             f"\\begin{{longtable}}{{{colspec}}}",
             f"\\caption{{{caption}}}",
             f"\\label{{{label}}}\\\\",
             TOPH, head, MIDH, "\\endfirsthead",
             "\\multicolumn{%d}{l}{\\textit{(continued)}}\\\\" % len(header.split("&")),
             TOPH, head, MIDH, "\\endhead",
             BOTH, "\\endfoot",
             BOTH]
    if notes:
        lines.append("\\multicolumn{%d}{p{0.92\\linewidth}}{\\footnotesize %s}\\\\"
                     % (len(header.split("&")), notes))
    lines.append("\\endlastfoot")
    lines += [r if r in (MIDH,) else r + " \\\\" for r in rows]
    lines += ["\\end{longtable}", "\\endgroup"]
    return "\n".join(lines) + "\n"


def comparison(tree=ATRAIN, arm="", radius="r100km"):
    sfx = f"{arm}_" if arm else ""
    df = pd.read_csv(tree / f"tccon_comparison_{sfx}{radius}.csv")
    return df[(df.qf_group == "all") & (df.surface == "all")].copy()


def dl_pool(b, u):
    """DerSimonian–Laird random-effects pool. Returns (mu, se, tau, I2, n).

    Cases without a finite (b, u) pair are dropped, matching the report md
    (e.g. the one r50 station-day whose budget could not be evaluated).
    """
    b, u = np.asarray(b, float), np.asarray(u, float)
    ok = np.isfinite(b) & np.isfinite(u)
    b, u = b[ok], u[ok]
    w = 1.0 / u**2
    mu_fe = np.sum(w * b) / np.sum(w)
    q = np.sum(w * (b - mu_fe)**2)
    s = len(b)
    tau2 = max(0.0, (q - (s - 1)) / (np.sum(w) - np.sum(w**2) / np.sum(w)))
    ws = 1.0 / (u**2 + tau2)
    mu = np.sum(ws * b) / np.sum(ws)
    se = np.sum(ws) ** -0.5
    i2 = max(0.0, (q - (s - 1)) / q) if q > 0 else 0.0
    return mu, se, np.sqrt(tau2), i2, s


# ---------------------------------------------------------------------------
# Appendix A
# ---------------------------------------------------------------------------

def tabA1():
    import sys
    sys.path.insert(0, str(REPO / "src"))
    from constants import FIT_ORDER
    from spectral.cumulant_fit import SAVGOL_WINDOW, SAVGOL_ORDER
    rows = [
        "\\multicolumn{2}{l}{\\textit{Spectral windows and inputs}}",
        "Bands & O$_2$A, WCO$_2$, SCO$_2$ (all three fitted independently)",
        "Transmittance & measured radiance / per-sounding TOA solar irradiance",
        "Solar irradiance & high-resolution solar line list, evaluated in the "
        "solar rest frame (per-sounding Doppler chain: atmosphere $\\to$ "
        "instrument $\\to$ solar frame)",
        "Channel ordinate & channel slant optical depth (SOD) from the "
        "meteorology-driven gas absorption computed per sounding",
        MIDH,
        "\\multicolumn{2}{l}{\\textit{Estimator}}",
        f"Polynomial order & {FIT_ORDER[0]} / {FIT_ORDER[1]} / {FIT_ORDER[2]} "
        "(O$_2$A / WCO$_2$ / SCO$_2$) in SOD, fitted to $\\ln T$",
        "Solver & exact linear least squares (SVD); bounded BVLS fallback "
        "where the unbounded solution violates the sign bounds",
        "Presmoothing & none (production); a Savitzky--Golay twin fit "
        f"(window {SAVGOL_WINDOW} channels, order {SAVGOL_ORDER}) is retained "
        "as a robustness variant (Fig.~A2)",
        MIDH,
        "\\multicolumn{2}{l}{\\textit{Quality control}}",
        "Channel mask & channels with unphysical transmittance ($T>1$) or "
        "non-finite $\\ln T$/SOD are dropped",
        "Minimum channels & fit skipped when fewer than (order$+$2) valid "
        "channels remain in a band",
        "Post-fit masks & non-positive fitted var($l'$) invalidates the "
        "gamma-shape diagnostics; unphysical retrieved XCO$_2$ ($\\le 0$) is "
        "masked before analysis",
    ]
    cap = ("Spectral-fit configuration and quality control of the production "
           "cumulant estimator (Sect.~3.2), read from the fitting source code. "
           "The polynomial orders follow the per-band slant-optical-depth "
           "dynamic range; the no-presmoothing fit is the production variant.")
    return table("lp{0.62\\linewidth}", "Component & Setting", rows, cap,
                 "tab:fit-config", size="\\footnotesize")


# ---------------------------------------------------------------------------
# Appendix B
# ---------------------------------------------------------------------------

def tabB1():
    import pyarrow.parquet as pq
    cols = ["sfc_type", "cld_dist_km", "xco2_bc_anomaly_r05",
            "xco2_bc_anomaly_r15"]
    df = pq.read_table(PARQUET, columns=cols).to_pandas()
    n_all = len(df)
    n_cld = int(df.cld_dist_km.notna().sum())
    oc, la = df[df.sfc_type == 0], df[df.sfc_type == 1]
    n_oc, n_la = len(oc), len(la)
    n_oc_lab = int(oc.xco2_bc_anomaly_r05.notna().sum())
    n_la_lab = int(la.xco2_bc_anomaly_r15.notna().sum())

    ln = pd.read_csv(REPO / "results" / "label_noise_ceiling_140dates.csv")
    n140 = int(ln[(ln.target == "r10") & (ln.subset == "all")].n.sum())

    cmp_at = comparison()
    cmp_dr = comparison(DEBASE / "drift")
    atom = pd.read_csv(DEBASE / "atom" / "atom_pseudo_column_results.csv")
    ship = pd.read_csv(DEBASE / "ship" / "ship_comparison_summary.csv")

    def f(n):
        return f"{n:,}".replace(",", "\\,")

    rows = [
        "\\multicolumn{3}{l}{\\textit{Training and analysis cohort "
        "(116 dates, 2016--2020)}}",
        f"Fitted soundings in the analysis dataset & {f(n_all)} & all rows of "
        "the combined feature dataset",
        f"\\quad with a valid nearest-cloud distance & {f(n_cld)} & "
        f"{100 * n_cld / n_all:.1f}\\,\\% of the cohort",
        f"\\quad ocean glint & {f(n_oc)} & surface type 0",
        f"\\quad land glint & {f(n_la)} & surface type 1",
        f"Ocean labeled (r05 anomaly target) & {f(n_oc_lab)} & "
        "clear-sky reference exists (Table~\\ref{tab:target-params})",
        f"Land labeled (r15 anomaly target) & {f(n_la_lab)} & "
        "clear-sky reference exists",
        MIDH,
        "\\multicolumn{3}{l}{\\textit{Label-noise-ceiling cohort "
        "(140 dates; Appendix~C)}}",
        f"Labeled soundings (r10 target) & {f(n140)} & superset used only for "
        "the ceiling derivation of Table~\\ref{tab:label-noise}",
        MIDH,
        "\\multicolumn{3}{l}{\\textit{Evaluation populations "
        "(dates disjoint from training; Table~\\ref{tab:dates_comparison})}}",
        f"TCCON A-Train station-days & {len(cmp_at)} & "
        f"{f(int(cmp_at.n_oco.sum()))} footprints, 18 sites",
        f"TCCON free-drift station-days & {len(cmp_dr)} & "
        f"{f(int(cmp_dr.n_oco.sum()))} footprints, 7 sites",
        f"ATom profile legs & {len(atom)} & "
        f"{f(int(atom.n_oco.sum()))} footprints, 8 dates",
        f"Ship overpasses & {len(ship)} & "
        f"{f(int(ship.n.sum()))} footprints, 2 cruises",
    ]
    cap = ("Cohort inventory and attrition from fitted soundings to labeled "
           "training populations and evaluation samples. The 116-date cohort "
           "is the manuscript analysis population; the 140-date cohort exists "
           "only for the label-noise-ceiling derivation.")
    return table("lrp{0.42\\linewidth}", "Population & $n$ & Definition",
                 rows, cap, "tab:cohort-attrition", size="\\footnotesize")


def tabB2():
    import sys
    sys.path.insert(0, str(REPO / "src"))
    from constants import (ANOMALY_LAT_THRES_DEG, ANOMALY_STD_THRES_PPM,
                           ANOMALY_MIN_CLD_DIST_KM, AQUA_FREE_DRIFT_YEAR,
                           MODIS_MATCH_BUFFER_PRE_DRIFT_MIN,
                           MODIS_MATCH_BUFFER_MIN, CLOUD_DIST_BAND_WIDTH_DEG,
                           CLOUD_DIST_BAND_OVERLAP_DEG)
    rows = [
        "\\multicolumn{2}{l}{\\textit{Cloud collocation (Sect.~3.1)}}",
        "MODIS granule matching window & "
        f"$\\pm{MODIS_MATCH_BUFFER_PRE_DRIFT_MIN}$\\,min before "
        f"{AQUA_FREE_DRIFT_YEAR}; $\\pm{MODIS_MATCH_BUFFER_MIN}$\\,min from "
        f"{AQUA_FREE_DRIFT_YEAR} (Aqua free drift)",
        "Cloud pixels kept & MYD35 Cloudy $+$ Uncertain (byte-1 bits 1--2); "
        "night-dominated granules skipped",
        "Distance search & KD tree per latitude band of width "
        f"{CLOUD_DIST_BAND_WIDTH_DEG}$^\\circ$ with "
        f"{CLOUD_DIST_BAND_OVERLAP_DEG}$^\\circ$ overlap buffer",
        MIDH,
        "\\multicolumn{2}{l}{\\textit{Clear-sky reference and anomaly target "
        "(Sect.~3.1)}}",
        "Reference latitude window & "
        f"$\\pm{ANOMALY_LAT_THRES_DEG}^\\circ$ along the same orbit",
        "Reference cloud-distance floor & ocean $\\ge$5\\,km (r05), land "
        "$\\ge$15\\,km (r15); r10 used for the common diagnostics",
        "Reference population guards & $\\ge$5 clear-sky soundings; "
        "reference standard deviation "
        f"$\\le{ANOMALY_STD_THRES_PPM:g}$\\,ppm, else no label",
        "Default reference floor (diagnostics) & "
        f"$\\ge${ANOMALY_MIN_CLD_DIST_KM:g}\\,km",
        MIDH,
        "\\multicolumn{2}{l}{\\textit{Deployment guards (applied to every "
        "corrected product)}}",
        "Climatology (input) guard & correction withheld when the base "
        "XCO$_2$ exceeds the prior by $>$50\\,ppm",
        "Anomaly-magnitude (output) guard & correction withheld when "
        "$|\\mu| > 25$\\,ppm",
    ]
    cap = ("Target-construction parameters and guards, read from the pipeline "
           "constants module and the deployment chain. The per-surface "
           "reference radii define the production anomaly labels; the two "
           "deployment guards set the correction to zero rather than "
           "extrapolating.")
    return table("lp{0.60\\linewidth}", "Parameter & Value", rows, cap,
                 "tab:target-params", size="\\footnotesize")


def tabB3():
    ln = pd.read_csv(REPO / "results" / "label_noise_ceiling_140dates.csv")
    prod = {"ocean": "r05", "land": "r15"}
    rows = []
    for surf in ["ocean", "land"]:
        rows.append(f"\\multicolumn{{6}}{{l}}{{\\textit{{{surf.capitalize()}"
                    f" ({prod[surf]} target)}}}}")
        for subset, slab in [("all", "all"), ("near<10km", "near-cloud ($<$10\\,km)")]:
            m = ln[(ln.surface == surf) & (ln.target == prod[surf])
                   & (ln.subset == subset)]
            assert len(m) == 1, (surf, subset, len(m))
            r = m.iloc[0]
            emp = f"{r.r2max_emp:.3f}" if np.isfinite(r.r2max_emp) else "--"
            rows.append(
                f"{slab} & {int(r.n):,}".replace(",", "\\,")
                + f" & {r.var_y:.3f} & {r.r2max_ref:.3f} & "
                  f"{r.r2max_ref_ret:.3f} & {emp}")
        if surf == "ocean":
            rows.append(MIDH)
    note = ("$R^2_{\\mathrm{max,ref}}$ (reference-sampling noise only) is the "
            "only hard bound; the retrieval-posterior and empirical far-field "
            "scenarios are stated noise levels that the anomaly target can "
            "legitimately exceed (Sect.~3.4 and Fig.~C4). Computed on the "
            "pooled 140-date cohort (Table~\\ref{tab:cohort-attrition}).")
    cap = ("Label-noise reference levels by surface and cloud-distance "
           "regime for the production anomaly targets: target variance and "
           "the maximum explainable $R^2$ under three noise scenarios "
           "(reference-mean sampling error only; additionally treating the "
           "retrieval posterior $\\sigma^2$ as noise; treating all far-field "
           "variance as noise).")
    return table("lrrrrr",
                 "Subset & $n$ & var($y$) & $R^2_{\\mathrm{max,ref}}$ & "
                 "$R^2_{\\mathrm{max,ref+ret}}$ & $R^2_{\\mathrm{max,emp}}$",
                 rows, cap, "tab:label-noise", notes=note)


# ---------------------------------------------------------------------------
# Appendix D
# ---------------------------------------------------------------------------

def tabD2():
    rows = []
    for radius, rlab in [("r100km", "100\\,km, $\\pm$60\\,min"),
                         ("r50km", "50\\,km, $\\pm$60\\,min")]:
        cmp = comparison(radius=radius).sort_values(["site", "date"])
        rows.append("\\multicolumn{9}{l}{\\textit{Coincidence radius "
                    + rlab + f" --- {len(cmp)} station-days}}}}")
        for _, r in cmp.iterrows():
            rows.append(
                f"{r.site} & {r.date} & {int(r.n_oco):,}".replace(",", "\\,")
                + f" & {r.cld_dist_mu:.1f} & {r.bias_raw:+.2f} & "
                  f"{r.bias_before:+.2f} & {r.bias_after:+.2f} & "
                  f"{r.rmse_before:.2f} & {r.rmse_after:.2f}")
        if radius == "r100km":
            rows.append(MIDH)
    note = ("Bias: station-day mean OCO-2 minus AK-harmonized TCCON (ppm) for "
            "the raw, operationally bias-corrected (before), and DE-corrected "
            "(after) products; RMSE: per-footprint root-mean-square error of "
            "the same comparison. $\\bar{d}_{\\mathrm{cld}}$: station-day "
            "mean nearest-cloud distance (km). Site codes in "
            "Table~\\ref{tab:tccon-stations-used}.")
    cap = ("Complete AK-harmonized station-day comparison metrics at the "
           "primary and robustness coincidence radii (all quality flags).")
    return longtable("llrrrrrrr",
                     "Site & Date & $n$ & $\\bar{d}_{\\mathrm{cld}}$ & "
                     "bias$_{\\mathrm{raw}}$ & bias$_{\\mathrm{B11}}$ & "
                     "bias$_{\\mathrm{DE}}$ & RMSE$_{\\mathrm{B11}}$ & "
                     "RMSE$_{\\mathrm{DE}}$",
                     rows, cap, "tab:stationday-metrics", notes=note)


def tabD3():
    def ci(m, lo, hi):
        return f"${m:+.2f}$ [{lo:+.2f}, {hi:+.2f}]"

    def pfmt(p):
        if p >= 1e-4:
            return f"{p:.4f}"
        mant, expo = f"{p:.1e}".split("e")
        return f"${mant}\\times10^{{{int(expo)}}}$"

    rows = []
    for radius, rlab in [("r100km", "100\\,km"), ("r50km", "50\\,km")]:
        sig = pd.read_csv(ATRAIN / f"tccon_significance_{radius}.csv")
        rows.append(f"\\multicolumn{{7}}{{l}}{{\\textit{{Radius {rlab}, "
                    "$\\pm$60\\,min}}")
        for qf, qlab in [("all", "0$+$1"), ("qf0", "0"), ("qf1", "1")]:
            for subset, slab in [("all", "all"),
                                 ("excl_ny", "excl.\\ ny")]:
                m = sig[(sig.qf_group == qf) & (sig.subset == subset)]
                if m.empty:
                    continue
                r = m.iloc[0]
                rows.append(
                    f"{qlab} & {slab} & {int(r.wilcoxon_absbias_n)} & "
                    f"{pfmt(r.wilcoxon_absbias_p)} & "
                    f"{pfmt(r.wilcoxon_rmse_p)} & "
                    + ci(r.d_mean_absbias_mean, r.d_mean_absbias_ci_lo,
                         r.d_mean_absbias_ci_hi)
                    + " & "
                    + ci(r.d_mean_rmse_mean, r.d_mean_rmse_ci_lo,
                         r.d_mean_rmse_ci_hi))
        if radius == "r100km":
            rows.append(MIDH)
    note = ("Wilcoxon: paired signed-rank test on station-day $|$bias$|$ and "
            "per-footprint RMSE (after vs.\\ before). $\\Delta$: site-clustered "
            "bootstrap mean change [95\\,\\% confidence interval] in the "
            "station-day mean $|$bias$|$ and mean fp-RMSE (ppm; negative = "
            "improvement). Site clustering resamples the 18 sites with "
            "replacement.")
    cap = ("Significance of the TCCON validation: paired Wilcoxon tests and "
           "site-clustered bootstrap changes for every quality-flag stratum, "
           "with and without the high-latitude station Ny-\\AA{}lesund "
           "(excl.\\ ny).")
    return longtable("llrrrll",
                     "QF & Sites & $n$ & $p_{|\\mathrm{bias}|}$ & "
                     "$p_{\\mathrm{RMSE}}$ & $\\Delta$mean$|$bias$|$ & "
                     "$\\Delta$mean fp-RMSE",
                     rows, cap, "tab:tccon-significance", notes=note,
                     size="\\scriptsize", colsep="3pt")


def tabD4():
    unc = pd.read_csv(ATRAIN / "tccon_uncertainty_r100km.csv")
    unc = unc[(unc.qf_group == "all") & (unc.surface == "all")]
    unc = unc.sort_values(["site", "date"])
    rows = []
    for _, r in unc.iterrows():
        rows.append(
            f"{r.site} & {r.date} & {r.D:+.2f} & {r.u_oco:.2f} & "
            f"{r.uTC_u_meas:.2f} & {r.uTC_u_temporal:.2f} & "
            f"{r.uTC_u_harm:.2f} & {r.uTC_u_colloc:.2f} & "
            f"{r.u_D:.2f} & {r.z:+.2f}")
    mu, se, tau, i2, _ = dl_pool(unc.D, unc.u_D)
    n_sig = int(unc.significant.sum())
    n_eq = int(unc.equivalent.sum())
    u50 = pd.read_csv(ATRAIN / "tccon_uncertainty_r50km.csv")
    u50 = u50[(u50.qf_group == "all") & (u50.surface == "all")]
    mu5, se5, tau5, i25, n5 = dl_pool(u50.D, u50.u_D)
    note = (f"DerSimonian--Laird pool (Appendix~\\ref{{app:DL_estimator}}): "
            f"$\\mu = {mu:+.2f} \\pm {se:.2f}$\\,ppm, $\\tau = {tau:.2f}$\\,ppm, "
            f"$I^2 = {100 * i2:.0f}\\,\\%$; {n_sig} of {len(unc)} cases differ "
            "significantly from zero ($|z|>1.96$) and "
            f"{n_eq} pass the $\\pm$0.5\\,ppm equivalence test. At the 50\\,km "
            f"radius: $\\mu = {mu5:+.2f} \\pm {se5:.2f}$\\,ppm, "
            f"$\\tau = {tau5:.2f}$\\,ppm, $I^2 = {100 * i25:.0f}\\,\\%$ "
            f"({n5} of {len(u50)} cases with an evaluable budget). "
            "$D$: corrected station-day mean difference "
            "to AK-harmonized TCCON; $u_{\\mathrm{OCO}}$: ensemble predictive "
            "term (effective-$n$, cloud-distance inflation); "
            "$u_{\\mathrm{meas}}$, $u_{\\mathrm{temp}}$, $u_{\\mathrm{harm}}$, "
            "$u_{\\mathrm{coll}}$: TCCON measurement, temporal-variability, "
            "harmonization, and collocation terms; $u_D$: quadrature total; "
            "$z = D/u_D$. All values in ppm.")
    cap = ("Per-station-day uncertainty budget of the corrected product at "
           "the primary 100\\,km radius, with the pooled random-effects "
           "summary (Fig.~\\ref{fig:unc_forest}).")
    return longtable("llrrrrrrrr",
                     "Site & Date & $D$ & $u_{\\mathrm{OCO}}$ & "
                     "$u_{\\mathrm{meas}}$ & $u_{\\mathrm{temp}}$ & "
                     "$u_{\\mathrm{harm}}$ & $u_{\\mathrm{coll}}$ & "
                     "$u_D$ & $z$",
                     rows, cap, "tab:unc_components", notes=note)


def tabD5():
    atom = pd.read_csv(DEBASE / "atom" / "atom_pseudo_column_results.csv")
    rows = []
    for _, r in atom.iterrows():
        rows.append(
            f"{r.date} & {int(r.profile_id)} ({r.leg_dir}) & "
            f"{r.lat:.1f} & {r.lon:.1f} & {int(r.n_oco)} & {r.cld_med:.1f} & "
            f"{r.atom_xco2_ak:.2f} & {r.resid_bc:+.2f} & {r.resid_corr:+.2f}")
    note = ("Residuals: OCO-2 minus ATom pseudo-column (ppm) for the "
            "operationally bias-corrected product and the DE-corrected "
            "product, per profile leg (AK-weighted pseudo-column construction "
            "of Sect.~3.5 and this appendix). $\\tilde{d}_{\\mathrm{cld}}$: "
            "median nearest-cloud distance of the collocated footprints (km).")
    cap = ("ATom leg inventory and residuals: the 17 collocated vertical "
           "profile legs over the eight usable dates (100\\,km, "
           "$\\pm$120\\,min).")
    return table("llrrrrrrr",
                 "Date & Leg & Lat.\\ & Lon.\\ & $n$ & "
                 "$\\tilde{d}_{\\mathrm{cld}}$ & "
                 "$X_{\\mathrm{CO_2}}^{\\mathrm{ATom}}$ & "
                 "res$_{\\mathrm{B11}}$ & res$_{\\mathrm{DE}}$",
                 rows, cap, "tab:atom-legs", notes=note,
                 size="\\footnotesize")


def tabD6():
    ship = pd.read_csv(DEBASE / "ship" / "ship_comparison_summary.csv")
    names = {"so268": "R/V Sonne SO268", "mr2101": "R/V Mirai MR21-01"}
    rows = []
    for _, r in ship.iterrows():
        rows.append(
            f"{r.date} & {names.get(r.ship, r.ship)} & {int(r.n)} & "
            f"{r.cld_med:.1f} & {r.ship_xco2:.2f} & {r.oco_bc:.2f} & "
            f"{r.oco_corr:.2f} & {r.resid_bc:+.2f} & {r.resid_corr:+.2f}")
    note = ("Residuals: OCO-2 minus shipborne EM27/SUN column (ppm). "
            "$\\tilde{d}_{\\mathrm{cld}}$: median nearest-cloud distance (km). "
            "The shipborne columns carry an absolute-scale limitation "
            "(Sect.~4.6); the clear-day case 2019-06-22 serves as a negative "
            "control (Fig.~\\ref{app-fig:ship_far_cld}).")
    cap = ("Shipborne case inventory and residuals: the four collocated "
           "overpasses of the two cruises.")
    return table("llrrrrrrr",
                 "Date & Cruise & $n$ & $\\tilde{d}_{\\mathrm{cld}}$ & "
                 "$X_{\\mathrm{CO_2}}^{\\mathrm{ship}}$ & "
                 "$X_{\\mathrm{CO_2}}^{\\mathrm{B11}}$ & "
                 "$X_{\\mathrm{CO_2}}^{\\mathrm{DE}}$ & "
                 "res$_{\\mathrm{B11}}$ & res$_{\\mathrm{DE}}$",
                 rows, cap, "tab:ship-cases", notes=note,
                 size="\\footnotesize")


# ---------------------------------------------------------------------------
# Appendix E
# ---------------------------------------------------------------------------

def tabE1():
    w = pd.read_csv(DEBASE / "failure_modes" / "worseners_r100km.csv")
    w = w[(w.tree == "atrain") & w.worse_bias].sort_values(
        "d_absbias", ascending=False)

    def cat(r):
        flip = np.sign(r.bias_after) != np.sign(r.bias_before)
        if abs(r.bias_before) <= 0.3:
            return "near-zero start"
        return "overshoot (sign flip)" if flip else "amplified"

    rows = []
    for _, r in w.iterrows():
        rows.append(
            f"{r.site} & {r.date} & {int(r.n_oco):,}".replace(",", "\\,")
            + f" & {r.cld_dist_mu:.1f} & {r.bias_before:+.2f} & "
              f"{r.bias_after:+.2f} & {r.d_absbias:+.2f} & "
              f"{r.d_rmse:+.2f} & {cat(r)}")
    n_rmse_ok = int((w.d_rmse < 0).sum())
    note = ("Worsened station-days: $|$bias$_{\\mathrm{DE}}| > "
            "|$bias$_{\\mathrm{B11}}|$ against the AK-harmonized reference "
            f"(median $\\Delta|$bias$| = {w.d_absbias.median():+.2f}$\\,ppm). "
            "Category: near-zero start = initial $|$bias$| \\le 0.3$\\,ppm "
            "(below the sign-flip floor of the within-overpass scatter); "
            "overshoot = the correction crosses zero; amplified = the "
            "residual grows with unchanged sign. The per-footprint RMSE "
            f"still improves in {n_rmse_ok} of {len(w)} of these cases "
            "($\\Delta$RMSE $<0$), consistent with a common-mode residual "
            "rather than a per-footprint mis-correction (Sect.~4.4).")
    cap = ("All station-days whose mean $|$bias$|$ worsens after correction "
           "(primary 100\\,km comparison, all quality flags), with the "
           "arithmetic category of the worsening.")
    return longtable("llrrrrrrl",
                     "Site & Date & $n$ & $\\bar{d}_{\\mathrm{cld}}$ & "
                     "bias$_{\\mathrm{B11}}$ & bias$_{\\mathrm{DE}}$ & "
                     "$\\Delta|$bias$|$ & $\\Delta$RMSE & Category",
                     rows, cap, "tab:worsening-cases", notes=note)


def tabE2():
    drivers = [("alb_o2a", "O$_2$A albedo"), ("snow_flag", "snow flag"),
               ("aod_total", "total AOD"), ("abs_lat", "$|$latitude$|$"),
               ("de_sigma", "predictive $\\sigma$")]
    rows = []
    for surf in ["ocean", "land"]:
        st = pd.read_csv(DEBASE / "failure_modes" / f"strat_{surf}_r100km.csv")
        rows.append(f"\\multicolumn{{8}}{{l}}{{\\textit{{{surf.capitalize()}}}}}")
        for key, lab in drivers:
            d = st[st.driver == key].sort_values("lo").reset_index(drop=True)
            if d.empty:
                continue
            picks = [d.iloc[0], d.iloc[-1]] if len(d) > 1 else [d.iloc[0]]
            tags = (["low", "high"] if len(picks) == 2 else ["all"])
            for tag, r in zip(tags, picks):
                if key == "snow_flag":
                    rng = "no snow" if r.lo <= 0 else "snow/ice"
                else:
                    rng = f"{r.lo:.2g}--{r.hi:.2g}"
                rows.append(
                    f"{lab} & {tag} & {rng} & {int(r.n):,}".replace(",", "\\,")
                    + f" & {r.rmse_before:.2f} & {r.rmse_after:.2f} & "
                      f"{r.frac_worse:.2f} & {r.z2:.2f}")
        if surf == "ocean":
            rows.append(MIDH)
    note = ("Lowest/highest deciles of each driver on the TCCON comparison "
            "footprints (bin edges in the driver units; snow flag is binary). "
            "RMSE: per-footprint error against AK-harmonized TCCON before "
            "(B11) and after (DE) correction; frac.\\ worse: fraction of "
            "footprints whose error increases; $\\langle z^2\\rangle$: "
            "calibration ratio of the ensemble predictive $\\sigma$. The full "
            "decile-resolved curves are in Fig.~\\ref{app-fig:failure_modes}.")
    cap = ("Per-footprint performance in the extreme strata of the "
           "environmental drivers (primary 100\\,km TCCON comparison): "
           "bright surfaces, snow, aerosol load, latitude, and the ensemble "
           "predictive uncertainty.")
    return longtable("lllrrrrr",
                     "Driver & Decile & Range & $n$ & RMSE$_{\\mathrm{B11}}$ & "
                     "RMSE$_{\\mathrm{DE}}$ & frac.\\ worse & "
                     "$\\langle z^2\\rangle$",
                     rows, cap, "tab:driver-strata", notes=note,
                     size="\\scriptsize", colsep="3pt")


def tabE3():
    cv = pd.read_csv(DEBASE / "failure_modes"
                     / "strat_cv_land_alb_o2a_r100km.csv")
    rows = []
    for i, r in cv.iterrows():
        lo = "$-\\infty$" if not np.isfinite(r.lo) else f"{r.lo:.2f}"
        hi = "$\\infty$" if not np.isfinite(r.hi) else f"{r.hi:.2f}"
        rows.append(
            f"{i + 1} & {lo}--{hi} & {int(r.n):,}".replace(",", "\\,")
            + f" & {r.rmse_no_corr:.2f} & {r.rmse_after:.2f} & "
              f"{r.frac_worse:.2f} & {r.z2:.2f}")
    note = ("Same albedo decile edges as the TCCON stratification "
            "(Table~\\ref{tab:driver-strata}). RMSE$_0$: anomaly-label RMSE "
            "with no correction applied; RMSE$_{\\mathrm{DE}}$: held-out "
            "residual RMSE of the correction; frac.\\ worse: fraction of "
            "footprints where applying the correction increases the error "
            "against the held-out anomaly label; $\\langle z^2\\rangle$: "
            "calibration ratio. The bright-surface failure signature seen "
            "against TCCON (frac.\\ worse 0.50) is absent here, identifying "
            "the remaining bright-surface TCCON residual as a "
            "within-overpass common-mode component outside the anomaly "
            "target (Sect.~4.4).")
    cap = ("Held-out cross-validation residuals of the land ensemble "
           "stratified by O$_2$A-band albedo.")
    return table("clrrrrr",
                 "Decile & Range & $n$ & RMSE$_0$ & RMSE$_{\\mathrm{DE}}$ & "
                 "frac.\\ worse & $\\langle z^2\\rangle$",
                 rows, cap, "tab:cv-albedo", notes=note,
                 size="\\footnotesize")


def tabE4():
    sm = ATRAIN / "smoother_null"
    arms = [("de", "Deep ensemble"), ("smoother_w10", "Smoother $\\pm$10\\,s"),
            ("smoother_w30", "Smoother $\\pm$30\\,s"),
            ("smoother_w100", "Smoother $\\pm$100\\,s")]
    first = comparison(sm, "de")
    rows = ["Before (B11 product) & "
            f"{first.bias_before.abs().mean():.2f} & "
            f"{np.sqrt((first.bias_before**2).mean()):.2f} & "
            f"{first.rmse_before.mean():.2f} & "
            f"{first.orig_sd.mean():.2f}", MIDH]
    for arm, lab in arms:
        c = comparison(sm, arm)
        assert len(c) == len(first)
        rows.append(f"{lab} & {c.bias_after.abs().mean():.2f} & "
                    f"{np.sqrt((c.bias_after**2).mean()):.2f} & "
                    f"{c.rmse_after.mean():.2f} & "
                    f"{c.corr_sd.mean():.2f}")
    note = ("Orbit-local running means over $|t' - t| \\le W$ within the same "
            "orbit segment and surface ($W = 10/30/100$\\,s $\\approx$ "
            "$\\pm$67/200/675\\,km along track), applied to the identical "
            "footprints, guards, and TCCON chain as the deep ensemble. "
            "Scatter: mean within-overpass standard deviation of the "
            "product. The smoothers collapse the scatter more strongly than "
            "the deep ensemble but do not reproduce its station-day bias "
            "reduction (Sect.~4.5, Figs.~10 and "
            "\\ref{app-fig:smoother_null_full}).")
    cap = ("Feature-free smoother null, full numerical results over the 75 "
           "station-days (AK-harmonized, 100\\,km, $\\pm$60\\,min): "
           "station-day mean $|$bias$|$, RMS bias, mean per-footprint RMSE, "
           "and mean within-overpass scatter for every tested window.")
    return table("lrrrr",
                 "Product & mean$|$bias$|$ & RMS bias & mean fp-RMSE & "
                 "scatter",
                 rows, cap, "tab:smoother-null", notes=note)


# ---------------------------------------------------------------------------
# Appendix F
# ---------------------------------------------------------------------------

def tabF1():
    sl = pd.read_csv(REPO / "workspace" / "spec_case_study"
                     / "shortlist_2026-07-08.csv")
    cats = [("good_land", "Real cloud, land"),
            ("good_ocean", "Real cloud, ocean"),
            ("false_positive", "MYD35 false positive"),
            ("cloud_no_bias", "Visible cloud without XCO$_2$ response")]
    vetted = {("2018-05-01"): "vetted showcase (Fig.~F1, Tasman Sea)",
              ("2019-02-01"): "vetted (N.\\ Pacific)",
              ("2019-08-01"): "vetted false positive (Botswana; RGB-confirmed)"}
    rows = []
    for key, lab in cats:
        d = sl[sl.category == key]
        rows.append(f"\\multicolumn{{4}}{{l}}{{\\textit{{{lab}"
                    f" --- {len(d)} cases}}}}")
        for _, r in d.iterrows():
            rows.append(f"{r.date} & \\texttt{{{r.frame}}} & {int(r.fp)} & "
                        f"{vetted.get(r.date, '')}")
        if key != cats[-1][0]:
            rows.append(MIDH)
    note = ("Screened from the cross-swath contrast statistic of the "
            "case-study screener (frame = 10-footprint OCO-2 frame "
            "identifier; fp = tracked footprint column). Three cases were "
            "additionally vetted against the MODIS Aqua true-colour scene; "
            "the RGB vetting is load-bearing for the false-positive category "
            "(the flagged Botswana scene is cloud-free in the imagery). The "
            "per-case atlas pages are in Supplement Sect.~S3.")
    cap = ("Vetted case-study inventory and category assignments for the "
           "case atlas (Appendix~F and Supplement Sect.~S3).")
    return longtable("llrp{0.34\\linewidth}", "Date & Frame & Fp & Note",
                     rows, cap, "tab:case-inventory", notes=note)


def tabF2():
    pp = DEBASE / "nassar_plumes" / "plume_preservation"
    k1 = pd.read_csv(pp / "nassar_k1_contrast.csv")
    k1 = k1[k1.gate == "all"]
    cn = pd.read_csv(pp / "nassar_control_null.csv")
    merged = cn.merge(k1, on=["plant_id", "date"], how="left")
    names = {"lipetsk": "Lipetsk", "kozienice": "Kozienice", "taean": "Taean",
             "westar": "Westar", "ghent": "Ghent"}
    verd = {"consistent_with_controls": "pass",
            "plant_collapses_more": "flagged"}
    rows = []
    for _, r in merged.sort_values(["date"]).iterrows():
        if np.isfinite(r.get("d_xco2_ppm", np.nan)):
            dx = f"${r.d_xco2_ppm:+.2f} \\pm {r.d_xco2_se:.2f}$"
            dm = f"${r.d_mu_ppm:+.2f} \\pm {r.d_mu_se:.2f}$"
            bound = f"{r.mu_from_plume_k1_bound_ppm:.2f}"
        else:
            dx = dm = bound = "--"
        rows.append(
            f"{names.get(r.plant_id, r.plant_id)} & {r.date} & "
            f"{int(r.plant_n)} & {r.plant_median_cld_km:.1f} & {dx} & {dm} & "
            f"{bound} & {r.plant_ratio_pctile_in_controls:.0f} & "
            f"{verd.get(r.verdict, r.verdict)}")
    note = ("$\\Delta X_{\\mathrm{CO_2}}$: plant-window minus background "
            "contrast of the B11 product ($\\pm$1\\,SE); $\\Delta\\mu$: same "
            "contrast of the applied correction. Bound: worst-case plume "
            "removal attributable to the spectral channel, from the "
            "background $\\mu$-vs-$k_1$ slope and the plume-window $k_1$ "
            "contrast (ppm). Pct.: percentile of the plant-window "
            "variability-collapse ratio within the matched plume-free "
            "control windows; verdict: pass = consistent with the controls, "
            "flagged = the plant window collapses more than its controls. "
            "The two flagged "
            "windows carry an all-band $k_1$ signature and are resolved as "
            "cloud contamination, not plume removal (Fig.~F3; "
            "$\\Delta X_{\\mathrm{CO_2}}$/$\\Delta\\mu$ dashes: windows with "
            "no renderable band contrast). Channel attribution in "
            "Table~\\ref{tab:nassar-attribution}.")
    cap = ("Per-case plume-preservation bounds and matched control-null "
           "results for the audited Nassar power-plant overpasses "
           "(case inventory in Fig.~F2).")
    return longtable("llrrllrrl",
                     "Plant & Date & $n$ & $\\tilde{d}_{\\mathrm{cld}}$ & "
                     "$\\Delta X_{\\mathrm{CO_2}}$ & $\\Delta\\mu$ & Bound & "
                     "Pct.\\ & Verdict",
                     rows, cap, "tab:plume-bounds", notes=note,
                     size="\\scriptsize")


# ---------------------------------------------------------------------------

ALL_ITEMS = {
    "tabA1": (tabA1, "tabA1_fitting_config.tex"),
    "tabB1": (tabB1, "tabB1_cohort_attrition.tex"),
    "tabB2": (tabB2, "tabB2_target_params.tex"),
    "tabB3": (tabB3, "tabB3_label_noise_ceilings.tex"),
    "tabD2": (tabD2, "tabD2_stationday_metrics.tex"),
    "tabD3": (tabD3, "tabD3_significance_tests.tex"),
    "tabD4": (tabD4, "tabD4_uncertainty_components.tex"),
    "tabD5": (tabD5, "tabD5_atom_legs.tex"),
    "tabD6": (tabD6, "tabD6_ship_cases.tex"),
    "tabE1": (tabE1, "tabE1_worsening_cases.tex"),
    "tabE2": (tabE2, "tabE2_driver_strata.tex"),
    "tabE3": (tabE3, "tabE3_cv_albedo.tex"),
    "tabE4": (tabE4, "tabE4_smoother_null.tex"),
    "tabF1": (tabF1, "tabF1_case_inventory.tex"),
    "tabF2": (tabF2, "tabF2_plume_bounds.tex"),
}


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--only", nargs="+", choices=sorted(ALL_ITEMS),
                    help="generate only these tables")
    args = ap.parse_args()
    for key in (args.only or ALL_ITEMS):
        fn, fname = ALL_ITEMS[key]
        write(fname, fn())


if __name__ == "__main__":
    main()
