"""
compare_shadow_brightening_samesfc.py
=====================================
Before/after comparison for the "no mixed-surface reference window" filter on
the Fig.-6 (shadow / brightening) statistics.

BEFORE = results/.../spec_sensitivity/prodref/shadow_brightening_stats.csv
         (all targets, production r15/r05 reference)
AFTER  = .../shadow_brightening_stats_samesfc.csv
         (same run with --exclude-mixed-ref: targets whose clear-sky reference
          window holds >= 1 footprint of the other surface type are dropped)

Writes, into .../prodref/mixed_surface_windows/ :
  shadow_brightening_samesfc_comparison.csv   every (surface, variable, branch,
      bin): n / mean / sem before and after, the difference, and the difference
      in units of the BEFORE standard error.
  shadow_brightening_samesfc_comparison.md    the same for land plus the
      headline numbers the manuscript quotes.

Usage
-----
    PYTHONPATH=src:workspace python workspace/compare_shadow_brightening_samesfc.py
"""

import argparse
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
PRODREF = (ROOT / "results/figures/cld_dist_analysis/spec_sensitivity/prodref")
OUTDIR = PRODREF / "mixed_surface_windows"

BIN_ORDER = ["0–1", "1–2", "2–3", "3–5", "5–7", "7–10"]
VAR_ORDER = ["dk1_o2a", "dk1_wco2", "dk1_sco2", "xco2_bc_anomaly"]
BRANCH_ORDER = ["brightened", "neutral", "shadowed"]
KEYS = ["surface", "variable", "branch", "cld_bin"]


def pooled(g: pd.DataFrame, mcol: str, scol: str, ncol: str) -> tuple:
    """n-weighted pooled mean over bins and its standard error."""
    m = g[mcol].to_numpy(float)
    s = g[scol].to_numpy(float)
    n = g[ncol].to_numpy(float)
    ok = np.isfinite(m) & np.isfinite(s) & (n > 0)
    if not ok.any():
        return np.nan, np.nan, 0.0
    m, s, n = m[ok], s[ok], n[ok]
    tot = n.sum()
    return float((n * m).sum() / tot), float(np.sqrt(((n * s) ** 2).sum()) / tot), float(tot)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[2])
    ap.add_argument("--before", default=str(PRODREF / "shadow_brightening_stats.csv"))
    ap.add_argument("--after", default=str(PRODREF / "shadow_brightening_stats_samesfc.csv"))
    ap.add_argument("--outdir", default=str(OUTDIR))
    args = ap.parse_args()

    outdir = Path(args.outdir)
    outdir.mkdir(parents=True, exist_ok=True)

    a = pd.read_csv(args.before).rename(
        columns={"mean": "mean_before", "sem": "sem_before", "n": "n_before"})
    b = pd.read_csv(args.after).rename(
        columns={"mean": "mean_after", "sem": "sem_after", "n": "n_after"})
    cmp = a.merge(b, on=KEYS, how="outer")
    cmp["n_dropped"] = cmp["n_before"] - cmp["n_after"]
    cmp["diff"] = cmp["mean_after"] - cmp["mean_before"]
    cmp["diff_over_sem_before"] = cmp["diff"] / cmp["sem_before"]
    cmp["rel_diff"] = cmp["diff"] / cmp["mean_before"].abs()
    cmp["variable"] = pd.Categorical(cmp["variable"], VAR_ORDER, ordered=True)
    cmp["branch"] = pd.Categorical(cmp["branch"], BRANCH_ORDER, ordered=True)
    cmp["cld_bin"] = pd.Categorical(cmp["cld_bin"], BIN_ORDER, ordered=True)
    cmp = cmp.sort_values(["surface"] + KEYS[1:]).reset_index(drop=True)
    cmp.to_csv(outdir / "shadow_brightening_samesfc_comparison.csv", index=False)

    land = cmp[cmp["surface"] == "land"]
    ocean = cmp[cmp["surface"] == "ocean"]

    # ── headline: pooled per-branch XCO2 anomaly and the branch separation ────
    head = {}
    for sname, sub in (("land", land), ("ocean", ocean)):
        x = sub[sub["variable"] == "xco2_bc_anomaly"]
        for br in BRANCH_ORDER:
            g = x[x["branch"] == br]
            for tag in ("before", "after"):
                m, s, n = pooled(g, f"mean_{tag}", f"sem_{tag}", f"n_{tag}")
                head[(sname, br, tag)] = (m, s, n)

    def sep(sname, tag):
        mb, sb, _ = head[(sname, "brightened", tag)]
        ms, ss, _ = head[(sname, "shadowed", tag)]
        return mb - ms, float(np.hypot(sb, ss))

    lines = ["# Fig. 6 before/after the no-mixed-surface-reference filter\n",
             "Generated by `workspace/compare_shadow_brightening_samesfc.py`.  "
             "BEFORE = all Fig.-6 targets, AFTER = targets whose production "
             "clear-sky reference window contains no footprint of the other "
             "surface type.\n"]

    lines.append("## Population\n")
    lines.append("| surface | targets before | targets after | dropped | dropped % |")
    lines.append("|---|---|---|---|---|")
    for sname, sub in (("land", land), ("ocean", ocean)):
        x = sub[sub["variable"] == "xco2_bc_anomaly"]
        nb, na = x["n_before"].sum(), x["n_after"].sum()
        lines.append(f"| {sname} | {int(nb):,} | {int(na):,} | {int(nb-na):,} | "
                     f"{100*(nb-na)/nb:.2f} % |")
    lines.append("")

    lines.append("## Headline numbers\n")
    for sname in ("land", "ocean"):
        lines.append(f"**{sname}**\n")
        lines.append("| branch | pooled ΔXCO₂ before (ppm) | pooled ΔXCO₂ after (ppm) "
                     "| change | change / SE_before |")
        lines.append("|---|---|---|---|---|")
        for br in BRANCH_ORDER:
            mb, sb, _ = head[(sname, br, "before")]
            ma, sa, _ = head[(sname, br, "after")]
            lines.append(f"| {br} | {mb:+.4f} ± {sb:.4f} | {ma:+.4f} ± {sa:.4f} | "
                         f"{ma-mb:+.4f} | {(ma-mb)/sb:+.2f} |")
        db, sdb = sep(sname, "before")
        da, sda = sep(sname, "after")
        lines.append(f"| **brightened − shadowed** | {db:+.4f} ± {sdb:.4f} | "
                     f"{da:+.4f} ± {sda:.4f} | {da-db:+.4f} | {(da-db)/sdb:+.2f} |")
        lines.append("")

    # per-bin brightened - shadowed separation (land)
    lines.append("## Land: brightened − shadowed ΔXCO₂ separation per bin (ppm)\n")
    lines.append("| bin (km) | before | after | change |")
    lines.append("|---|---|---|---|")
    xl = land[land["variable"] == "xco2_bc_anomaly"]
    for bn in BIN_ORDER:
        r = {br: xl[(xl["branch"] == br) & (xl["cld_bin"] == bn)] for br in BRANCH_ORDER}
        vals = {}
        for tag in ("before", "after"):
            try:
                vals[tag] = (float(r["brightened"][f"mean_{tag}"].iloc[0])
                             - float(r["shadowed"][f"mean_{tag}"].iloc[0]))
            except (IndexError, ValueError):
                vals[tag] = np.nan
        lines.append(f"| {bn} | {vals['before']:+.4f} | {vals['after']:+.4f} | "
                     f"{vals['after']-vals['before']:+.4f} |")
    lines.append("")

    # largest movers
    fin = cmp[np.isfinite(cmp["diff_over_sem_before"])]
    for sname in ("land", "ocean"):
        s = fin[fin["surface"] == sname]
        if not len(s):
            continue
        big_abs = s.loc[s["diff"].abs().idxmax()]
        big_se = s.loc[s["diff_over_sem_before"].abs().idxmax()]
        lines.append(f"## Largest movers ({sname})\n")
        lines.append(f"- largest |Δmean|: {big_abs['variable']} / "
                     f"{big_abs['branch']} / {big_abs['cld_bin']} km: "
                     f"{big_abs['mean_before']:.5g} → {big_abs['mean_after']:.5g} "
                     f"(Δ {big_abs['diff']:+.5g} = "
                     f"{big_abs['diff_over_sem_before']:+.2f} SE_before, "
                     f"n {int(big_abs['n_before']):,} → {int(big_abs['n_after']):,})")
        lines.append(f"- largest |Δ| in SE units: {big_se['variable']} / "
                     f"{big_se['branch']} / {big_se['cld_bin']} km: "
                     f"{big_se['mean_before']:.5g} → {big_se['mean_after']:.5g} "
                     f"(Δ {big_se['diff']:+.5g} = "
                     f"{big_se['diff_over_sem_before']:+.2f} SE_before, "
                     f"n {int(big_se['n_before']):,} → {int(big_se['n_after']):,})")
        q = s["diff_over_sem_before"].abs()
        lines.append(f"- |Δ| in SE units: median {q.median():.2f}, "
                     f"90th pct {q.quantile(0.9):.2f}, max {q.max():.2f} "
                     f"over {len(s)} (variable, branch, bin) cells\n")

    lines.append("## Land: full panel table\n")
    lines.append("| variable | branch | bin (km) | n before | n after | mean before | "
                 "SE before | mean after | SE after | Δmean | Δ/SE_before |")
    lines.append("|---|---|---|---|---|---|---|---|---|---|---|")
    for _, r in land.iterrows():
        lines.append(
            f"| {r['variable']} | {r['branch']} | {r['cld_bin']} | "
            f"{int(r['n_before']):,} | {int(r['n_after']):,} | "
            f"{r['mean_before']:.5g} | {r['sem_before']:.3g} | "
            f"{r['mean_after']:.5g} | {r['sem_after']:.3g} | "
            f"{r['diff']:+.3g} | {r['diff_over_sem_before']:+.2f} |")
    lines.append("")

    (outdir / "shadow_brightening_samesfc_comparison.md").write_text("\n".join(lines))
    print("\n".join(lines[:60]))
    print(f"\nwrote {outdir/'shadow_brightening_samesfc_comparison.csv'}")
    print(f"wrote {outdir/'shadow_brightening_samesfc_comparison.md'}")


if __name__ == "__main__":
    main()
