#!/bin/env bash
# run_case list for the atrain-era new TCCON station-days (24 cases).
# Generated by workspace/newsites_cases.py; consumed by
# tccon_comparison_report.py --script (only the run_case lines are read).
# RADIUS_KM=100  WINDOW_MIN=60  AQUA_FREE_DRIFT_YEAR=2022
#------------------------------------------------------------------------------

# -- bialystok01 (bi) --
run_case  2015-03-23   bi20090313_20181001.public.qc.nc      22.47    22.66    52.36    52.55   397.5  402.5  land  poster bi  yes   # n=63 dmin=82km
run_case  2015-07-15   bi20090313_20181001.public.qc.nc      22.14    22.98    52.54    53.99   395.0  399.0  land  poster bi  yes   # n=47 dmin=50km
run_case  2018-06-03   bi20090313_20181001.public.qc.nc      22.13    22.60    52.51    53.43   404.0  408.5  land  poster bi  yes   # n=152 dmin=49km

# -- bremen01 (br) --
run_case  2018-08-07   br20060213_20250520.public.qc.nc       8.06     8.95    52.20    53.77   402.5  406.5  land  poster br  yes   # n=395 dmin=25km

# -- garmisch01 (gm) --
run_case  2015-02-13   gm20070718_20240116.public.qc.nc      10.76    11.69    46.67    48.36   398.0  406.5  land  poster gm  yes   # n=254 dmin=16km
run_case  2015-02-18   gm20070718_20240116.public.qc.nc      10.49    11.08    46.58    47.90   381.5  409.0  land  poster gm  yes   # n=59 dmin=23km
run_case  2015-07-14   gm20070718_20240116.public.qc.nc      11.65    11.90    46.77    47.31   394.0  402.0  land  poster gm  yes   # n=28 dmin=49km
run_case  2017-01-26   gm20070718_20240116.public.qc.nc      12.12    12.27    47.81    48.03   403.5  409.0  land  poster gm  yes   # n=37 dmin=96km
run_case  2019-06-14   gm20070718_20240116.public.qc.nc      11.98    12.20    47.61    48.11   410.0  413.5  land  poster gm  yes   # n=146 dmin=85km

# -- harwell01 (hw) --
run_case  2021-09-08   hw20210530_20260331.public.qc.nc      -0.51     0.03    51.20    52.32   410.0  413.0  land  poster hw  yes   # n=436 dmin=76km

# -- lauder02 (ll) --
run_case  2016-09-10   ll20100202_20180930.public.qc.nc     170.00   170.57   -45.75   -44.18   399.0  406.5  land  poster ll  yes   # n=571 dmin=42km

# -- lauder03 (lr) --
run_case  2019-06-22   lr20181002_20250629.public.qc.nc     168.76   169.21   -45.78   -44.65   401.0  414.5  land  poster lr  yes   # n=122 dmin=51km
run_case  2021-05-26   lr20181002_20250629.public.qc.nc     168.67   169.08   -45.71   -44.65   410.0  419.5  land  poster lr  yes   # n=49 dmin=61km
run_case  2021-09-08   lr20181002_20250629.public.qc.nc     170.09   170.61   -45.67   -44.22   406.0  417.0  land  poster lr  yes   # n=137 dmin=49km

# -- nicosia01 (ni) --
run_case  2020-12-23   ni20190901_20250525.public.qc.nc      33.97    34.41    34.79    35.90   413.0  416.5  ocean poster ni  yes   # n=324 dmin=76km

# -- sodankyla01 (so) --
run_case  2016-05-29   so20090516_20251025.public.qc.nc      25.16    27.01    66.48    68.10   402.0  405.0  land  poster so  yes   # n=567 dmin=22km
run_case  2018-09-08   so20090516_20251025.public.qc.nc      25.19    27.05    66.48    68.11   398.5  403.5  land  poster so  yes   # n=496 dmin=20km
run_case  2018-10-10   so20090516_20251025.public.qc.nc      26.33    26.92    67.23    67.52   401.5  406.0  land  poster so  yes   # n=919 dmin=1km
run_case  2019-06-09   so20090516_20251025.public.qc.nc      28.77    28.97    67.41    67.63   407.0  411.0  land  poster so  yes   # n=47 dmin=95km
run_case  2020-03-30   so20090516_20251025.public.qc.nc      26.99    28.32    66.77    67.99   413.0  417.0  land  poster so  yes   # n=32 dmin=48km

# -- tsukuba02 (tk) --
run_case  2015-03-17   tk20140328_20210331.public.qc.nc     139.92   140.55    35.21    36.92   399.5  404.0  both  poster tk  yes   # n=400 dmin=9km
run_case  2016-03-03   tk20140328_20210331.public.qc.nc     139.84   140.45    35.18    36.92   403.0  408.5  land  poster tk  yes   # n=646 dmin=0km
run_case  2017-01-17   tk20140328_20210331.public.qc.nc     139.29   139.78    35.19    36.48   403.5  411.0  both  poster tk  yes   # n=371 dmin=57km
run_case  2018-04-10   tk20140328_20210331.public.qc.nc     140.06   140.66    35.26    36.95   408.5  413.5  both  poster tk  yes   # n=269 dmin=22km
