#!/bin/env bash
# run_case list for the drift-era new TCCON station-days (3 cases).
# Generated by workspace/newsites_cases.py; consumed by
# tccon_comparison_report.py --script (only the run_case lines are read).
# RADIUS_KM=100  WINDOW_MIN=60  AQUA_FREE_DRIFT_YEAR=2022
#------------------------------------------------------------------------------

# -- garmisch01 (gm) --
run_case  2023-07-04   gm20070718_20240116.public.qc.nc      11.31    11.62    47.75    48.36   411.0  422.0  land  poster gm  yes   # n=25 dmin=52km

# -- hefei01 (hf) --
run_case  2024-05-10   hf20151102_20251230.public.qc.nc     116.21   116.39    31.63    32.27   424.5  427.5  land  poster hf  yes   # n=244 dmin=79km

# -- lauder03 (lr) --
run_case  2023-03-13   lr20181002_20250629.public.qc.nc     169.04   169.38   -45.38   -44.39   410.5  419.0  land  poster lr  yes   # n=63 dmin=26km
